#!/bin/bash

# Railway Deployment Fix Commands
# Generated: 2025-12-15
# Use these commands to investigate and fix failed Railway deployments

TOKEN="rw_Fe26.2**2fa9d729ce17c99b284ff1e06068f02a1c560550e582d84f5d3872351c449fe2*4adp_BYtD15a33HMztKvnw*bfN6Kv6SvzypR03GNMa9BdI3nDAX2xaySiLv9HFr3gBHtu4V3TvJIuFxcclrLTr7yWJzHKPZi_y067tSnN3PRg*1768379039138*c5c44983b39574bcc2a70f6d9c2b0ec79baf433c6440f6269118efa7a7927ced*7zrnxdg0AtKlA86zJDKe45lKoxYNxdeGd3wV4BDi1m0"

echo "================================"
echo "Railway Deployment Fix Commands"
echo "================================"
echo ""

# Function to check logs for a specific project
check_logs() {
    PROJECT_ID=$1
    PROJECT_NAME=$2

    echo "Checking logs for: $PROJECT_NAME"
    echo "Project ID: $PROJECT_ID"
    echo ""
    echo "To view logs manually:"
    echo "1. Visit: https://railway.app/project/$PROJECT_ID"
    echo "2. Or use Railway CLI:"
    echo "   cd /path/to/project && railway logs"
    echo ""
}

# Function to get deployment details
get_deployment_details() {
    PROJECT_ID=$1

    curl -s -X POST https://backboard.railway.com/graphql/v2 \
        -H "Authorization: Bearer $TOKEN" \
        -H "Content-Type: application/json" \
        -d "{\"query\":\"{ project(id: \\\"$PROJECT_ID\\\") { name services { edges { node { name deployments(first: 3) { edges { node { id status createdAt } } } } } } }\"}" | python3 -m json.tool
}

echo "=== CRITICAL FAILURES TO FIX FIRST ==="
echo ""

echo "1. BlackRoad Core - Project ID: 9d3d2549-3778-4c86-8afd-cefceaaa74d2"
echo "   URL: https://railway.app/project/9d3d2549-3778-4c86-8afd-cefceaaa74d2"
echo "   8 services failed - requires investigation"
echo ""

echo "2. blackroad-ai - Project ID: 93a857a5-368e-4d7b-ba5b-d92a8962f0eb"
echo "   URL: https://railway.app/project/93a857a5-368e-4d7b-ba5b-d92a8962f0eb"
echo ""

echo "3. blackroad-db - Project ID: 2c157d7c-680f-4d5c-892b-fb92e89be58b"
echo "   URL: https://railway.app/project/2c157d7c-680f-4d5c-892b-fb92e89be58b"
echo "   This is critical - other services may depend on it"
echo ""

echo "=== COMMANDS TO CHECK SPECIFIC PROJECT ==="
echo ""
echo "# Check BlackRoad Core"
echo "get_deployment_details 9d3d2549-3778-4c86-8afd-cefceaaa74d2"
echo ""
echo "# Check blackroad-ai"
echo "get_deployment_details 93a857a5-368e-4d7b-ba5b-d92a8962f0eb"
echo ""
echo "# Check blackroad-db"
echo "get_deployment_details 2c157d7c-680f-4d5c-892b-fb92e89be58b"
echo ""

echo "=== BULK REDEPLOY COMMANDS ==="
echo ""
echo "# To redeploy all services in a project via Railway CLI:"
echo "# 1. Link to project: railway link <project-id>"
echo "# 2. Select environment: railway environment"
echo "# 3. Redeploy: railway up"
echo ""

echo "=== FAILED PROJECTS BY PRIORITY ==="
echo ""
echo "HIGH PRIORITY (Fix first):"
echo "  - BlackRoad Core (8 services)"
echo "  - blackroad-ai"
echo "  - blackroad-db"
echo ""
echo "MEDIUM PRIORITY (Fix after high priority):"
echo "  - blackroad-analytics"
echo "  - blackroad-billing"
echo "  - blackroad-bookmarks"
echo "  - blackroad-cache"
echo "  - blackroad-cdn"
echo "  - blackroad-chat"
echo "  - blackroad-ci"
echo "  - blackroad-crawler"
echo "  - blackroad-crm"
echo "  - blackroad-dns"
echo "  - blackroad-docs"
echo "  - blackroad-firewall"
echo "  - blackroad-git"
echo "  - blackroad-meet"
echo "  - blackroad-mesh"
echo "  - blackroad-notes"
echo "  - blackroad-password"
echo "  - blackroad-pastebin"
echo "  - blackroad-proxy"
echo "  - blackroad-queue"
echo "  - blackroad-registry"
echo "  - blackroad-scheduler"
echo "  - blackroad-search"
echo "  - blackroad-sso"
echo "  - blackroad-uptime"
echo "  - blackroad-vault"
echo "  - blackroad-vpn"
echo "  - blackroad-wiki"
echo ""

echo "=== PROJECTS WITH NO DEPLOYMENTS ==="
echo ""
echo "These 20 projects have no services and can be:"
echo "  a) Deployed if needed"
echo "  b) Archived/deleted if not needed"
echo ""
echo "  - blackroad-agents-primary (NEW - created today)"
echo "  - blackroad-accounting"
echo "  - blackroad-backup"
echo "  - blackroad-boards"
echo "  - blackroad-calendar"
echo "  - blackroad-commerce"
echo "  - blackroad-diagrams"
echo "  - blackroad-forms"
echo "  - blackroad-identity"
echo "  - blackroad-kanban"
echo "  - blackroad-logs"
echo "  - blackroad-mail"
echo "  - blackroad-ml"
echo "  - blackroad-monitor"
echo "  - blackroad-pm"
echo "  - blackroad-secrets"
echo "  - blackroad-storage"
echo "  - blackroad-support"
echo "  - blackroad-workflow"
echo ""

echo "=== QUICK INVESTIGATION STEPS ==="
echo ""
echo "For each failed service:"
echo "1. Open Railway dashboard: https://railway.app/"
echo "2. Navigate to project"
echo "3. Click on service"
echo "4. Check 'Deployments' tab for error messages"
echo "5. Check 'Build Logs' for compilation errors"
echo "6. Check 'Deploy Logs' for runtime errors"
echo "7. Verify 'Variables' tab has all required env vars"
echo "8. Check 'Settings' for correct:"
echo "   - Start command"
echo "   - Build command"
echo "   - Root directory"
echo ""

echo "=== COMMON FIX PATTERNS ==="
echo ""
echo "Issue: Missing environment variables"
echo "Fix: Add vars in Railway dashboard -> Variables tab"
echo ""
echo "Issue: Build failure"
echo "Fix: Check package.json, requirements.txt, or Dockerfile"
echo ""
echo "Issue: Start command incorrect"
echo "Fix: Update in Settings -> Start Command"
echo ""
echo "Issue: Port binding"
echo "Fix: App should bind to 0.0.0.0:\$PORT"
echo ""

echo "=== USEFUL RAILWAY CLI COMMANDS ==="
echo ""
echo "# Install Railway CLI (if not installed)"
echo "npm i -g @railway/cli"
echo ""
echo "# Login (use token)"
echo "railway login --browserless"
echo "# Then paste token when prompted"
echo ""
echo "# Link to a project"
echo "railway link <project-id>"
echo ""
echo "# View logs"
echo "railway logs"
echo ""
echo "# View logs with follow"
echo "railway logs --follow"
echo ""
echo "# Check status"
echo "railway status"
echo ""
echo "# Deploy"
echo "railway up"
echo ""
echo "# Open in browser"
echo "railway open"
echo ""
echo "# List variables"
echo "railway variables"
echo ""
echo "# Set a variable"
echo "railway variables set KEY=VALUE"
echo ""

echo "================================"
echo "For detailed report, see:"
echo "/Users/alexa/blackroad-sandbox/RAILWAY_HEALTH_CHECK_REPORT.md"
echo "================================"
