/**
 * Service Registry
 * Central registry of all BlackRoad OS services
 */

import type { ServiceMetadata, ServiceId } from "./types";

export const SERVICE_REGISTRY: Record<ServiceId, ServiceMetadata> = {
  core: {
    id: "core",
    name: "BlackRoad OS Core",
    description: "Core library and shared types for BlackRoad OS",
    kind: "core",
    default_env: "local",
    health_path: "/health",
    ready_path: "/ready",
    version_path: "/version",
  },
  api: {
    id: "api",
    name: "BlackRoad OS API",
    description: "Main HTTP API server for BlackRoad OS",
    kind: "api",
    default_env: "staging",
    health_path: "/api/health",
    ready_path: "/api/ready",
    version_path: "/api/version",
  },
  operator: {
    id: "operator",
    name: "BlackRoad OS Operator",
    description: "Worker service for job processing and orchestration",
    kind: "worker",
    default_env: "staging",
    health_path: "/health",
    ready_path: "/ready",
    version_path: "/version",
  },
  web: {
    id: "web",
    name: "BlackRoad OS Web",
    description: "Web application frontend",
    kind: "web",
    default_env: "staging",
    health_path: "/api/health",
    ready_path: "/api/ready",
    version_path: "/api/version",
  },
  "prism-console": {
    id: "prism-console",
    name: "Prism Console",
    description: "Advanced console interface for BlackRoad OS",
    kind: "console",
    default_env: "staging",
    health_path: "/api/health",
    ready_path: "/api/ready",
    version_path: "/api/version",
  },
  "pack-education": {
    id: "pack-education",
    name: "Education Pack",
    description: "Agent pack for education-related tasks",
    kind: "pack",
    default_env: "staging",
    health_path: "/health",
    ready_path: "/ready",
    version_path: "/version",
  },
  "pack-infra-devops": {
    id: "pack-infra-devops",
    name: "Infrastructure & DevOps Pack",
    description: "Agent pack for infrastructure and DevOps automation",
    kind: "pack",
    default_env: "staging",
    health_path: "/health",
    ready_path: "/ready",
    version_path: "/version",
  },
  "pack-finance": {
    id: "pack-finance",
    name: "Finance Pack",
    description: "Agent pack for financial analysis and operations",
    kind: "pack",
    default_env: "staging",
    health_path: "/health",
    ready_path: "/ready",
    version_path: "/version",
  },
  "pack-legal": {
    id: "pack-legal",
    name: "Legal Pack",
    description: "Agent pack for legal document processing and compliance",
    kind: "pack",
    default_env: "staging",
    health_path: "/health",
    ready_path: "/ready",
    version_path: "/version",
  },
};
