/**
 * Tunnel Integrations
 *
 * Unified tunnel management for exposing local services.
 * Supports multiple tunnel providers for secure remote access.
 *
 * Features:
 * - Cloudflare Tunnels (cloudflared)
 * - ngrok tunnels
 * - localtunnel
 * - Tailscale Funnel
 * - SSH port forwarding
 */

// =============================================================================
// TYPES
// =============================================================================

export type TunnelProvider = 'cloudflare' | 'ngrok' | 'localtunnel' | 'tailscale' | 'ssh';

export interface TunnelConfig {
  provider: TunnelProvider;
  localPort: number;
  localHost?: string;
  protocol?: 'http' | 'https' | 'tcp' | 'tls';
  subdomain?: string;
  domain?: string;
  authToken?: string;
}

export interface TunnelInfo {
  id: string;
  provider: TunnelProvider;
  publicUrl: string;
  localUrl: string;
  status: 'connected' | 'connecting' | 'disconnected' | 'error';
  createdAt: Date;
  metrics?: {
    connections: number;
    bytesIn: number;
    bytesOut: number;
  };
}

// =============================================================================
// CLOUDFLARE TUNNEL CLIENT
// =============================================================================

export interface CloudflareTunnelConfig {
  accountId: string;
  tunnelSecret?: string;
  tunnelId?: string;
  tunnelName?: string;
}

export class CloudflareTunnelClient {
  private readonly config: CloudflareTunnelConfig;
  private readonly apiToken: string;

  constructor(apiToken: string, config: CloudflareTunnelConfig) {
    this.apiToken = apiToken;
    this.config = config;
  }

  /**
   * Generate cloudflared config YAML
   */
  generateConfig(ingress: { hostname: string; service: string; path?: string }[]): string {
    const config = {
      tunnel: this.config.tunnelId || this.config.tunnelName,
      'credentials-file': `/root/.cloudflared/${this.config.tunnelId}.json`,
      ingress: [
        ...ingress.map((i) => ({
          hostname: i.hostname,
          service: i.service,
          ...(i.path && { path: i.path }),
        })),
        { service: 'http_status:404' },
      ],
    };

    return `# Cloudflare Tunnel Configuration
# Generated by BlackRoad OS

tunnel: ${config.tunnel}
credentials-file: ${config['credentials-file']}

ingress:
${ingress.map((i) => `  - hostname: ${i.hostname}
    service: ${i.service}${i.path ? `\n    path: ${i.path}` : ''}`).join('\n')}
  - service: http_status:404
`;
  }

  /**
   * Generate Docker Compose for cloudflared
   */
  generateDockerCompose(tunnelToken: string): string {
    return `version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${tunnelToken}
    networks:
      - tunnel-network

networks:
  tunnel-network:
    driver: bridge
`;
  }

  /**
   * Generate systemd service for cloudflared
   */
  generateSystemdService(tunnelToken: string): string {
    return `[Unit]
Description=Cloudflare Tunnel
After=network.target

[Service]
Type=simple
User=root
ExecStart=/usr/local/bin/cloudflared tunnel --no-autoupdate run --token ${tunnelToken}
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
`;
  }

  /**
   * Generate installation script
   */
  generateInstallScript(): string {
    return `#!/bin/bash
# Cloudflare Tunnel Installation Script
# Generated by BlackRoad OS

set -e

echo "Installing cloudflared..."

# Detect OS
if [ -f /etc/debian_version ]; then
    # Debian/Ubuntu
    curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
    sudo dpkg -i cloudflared.deb
    rm cloudflared.deb
elif [ -f /etc/redhat-release ]; then
    # RHEL/CentOS/Fedora
    curl -L --output cloudflared.rpm https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-x86_64.rpm
    sudo rpm -i cloudflared.rpm
    rm cloudflared.rpm
elif [ "$(uname)" == "Darwin" ]; then
    # macOS
    brew install cloudflared
else
    # Generic Linux
    curl -L --output cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
    sudo mv cloudflared /usr/local/bin/
    sudo chmod +x /usr/local/bin/cloudflared
fi

echo "cloudflared installed successfully!"
cloudflared version
`;
  }
}

// =============================================================================
// NGROK TUNNEL CLIENT
// =============================================================================

export interface NgrokConfig {
  authToken: string;
  region?: 'us' | 'eu' | 'ap' | 'au' | 'sa' | 'jp' | 'in';
}

export class NgrokClient {
  private readonly config: NgrokConfig;
  private readonly baseUrl = 'https://api.ngrok.com';

  constructor(config: NgrokConfig) {
    this.config = config;
  }

  /**
   * Generate ngrok config YAML
   */
  generateConfig(tunnels: Record<string, { proto: string; addr: string | number; hostname?: string }>): string {
    return `# ngrok configuration
# Generated by BlackRoad OS

version: "2"
authtoken: ${this.config.authToken}
${this.config.region ? `region: ${this.config.region}` : ''}

tunnels:
${Object.entries(tunnels).map(([name, config]) => `  ${name}:
    proto: ${config.proto}
    addr: ${config.addr}${config.hostname ? `\n    hostname: ${config.hostname}` : ''}`).join('\n')}
`;
  }

  /**
   * Generate ngrok command for quick tunnel
   */
  generateCommand(options: {
    port: number;
    protocol?: 'http' | 'tcp' | 'tls';
    subdomain?: string;
    hostname?: string;
    auth?: string;
  }): string {
    let cmd = `ngrok ${options.protocol || 'http'} ${options.port}`;

    if (options.subdomain) {
      cmd += ` --subdomain=${options.subdomain}`;
    }
    if (options.hostname) {
      cmd += ` --hostname=${options.hostname}`;
    }
    if (options.auth) {
      cmd += ` --basic-auth="${options.auth}"`;
    }
    if (this.config.region) {
      cmd += ` --region=${this.config.region}`;
    }

    return cmd;
  }

  /**
   * Generate Docker command for ngrok
   */
  generateDockerCommand(port: number, protocol = 'http'): string {
    return `docker run -it --rm \\
  -e NGROK_AUTHTOKEN=${this.config.authToken} \\
  --network host \\
  ngrok/ngrok ${protocol} ${port}`;
  }
}

// =============================================================================
// LOCALTUNNEL CLIENT
// =============================================================================

export interface LocaltunnelConfig {
  subdomain?: string;
  host?: string;
}

export class LocaltunnelClient {
  private readonly config: LocaltunnelConfig;

  constructor(config: LocaltunnelConfig = {}) {
    this.config = {
      host: config.host || 'https://localtunnel.me',
      subdomain: config.subdomain,
    };
  }

  /**
   * Generate localtunnel command
   */
  generateCommand(port: number, options?: { subdomain?: string; localhost?: string }): string {
    let cmd = `lt --port ${port}`;

    if (options?.subdomain || this.config.subdomain) {
      cmd += ` --subdomain ${options?.subdomain || this.config.subdomain}`;
    }
    if (options?.localhost) {
      cmd += ` --local-host ${options.localhost}`;
    }
    if (this.config.host !== 'https://localtunnel.me') {
      cmd += ` --host ${this.config.host}`;
    }

    return cmd;
  }

  /**
   * Generate npm script for package.json
   */
  generateNpmScript(port: number, subdomain?: string): object {
    return {
      scripts: {
        tunnel: `lt --port ${port}${subdomain ? ` --subdomain ${subdomain}` : ''}`,
      },
    };
  }

  /**
   * Generate Node.js code for programmatic usage
   */
  generateNodeCode(port: number, subdomain?: string): string {
    return `const localtunnel = require('localtunnel');

async function startTunnel() {
  const tunnel = await localtunnel({
    port: ${port},
    ${subdomain ? `subdomain: '${subdomain}',` : ''}
    host: '${this.config.host}',
  });

  console.log('Tunnel URL:', tunnel.url);

  tunnel.on('close', () => {
    console.log('Tunnel closed');
  });

  tunnel.on('error', (err) => {
    console.error('Tunnel error:', err);
  });

  return tunnel;
}

startTunnel();
`;
  }
}

// =============================================================================
// TAILSCALE FUNNEL CLIENT
// =============================================================================

export interface TailscaleConfig {
  authKey?: string;
}

export class TailscaleClient {
  private readonly config: TailscaleConfig;

  constructor(config: TailscaleConfig = {}) {
    this.config = config;
  }

  /**
   * Generate Tailscale Funnel command
   */
  generateFunnelCommand(port: number, options?: { background?: boolean; https?: boolean }): string {
    let cmd = `tailscale funnel`;

    if (options?.https !== false) {
      cmd += ` --https=${port}`;
    } else {
      cmd += ` ${port}`;
    }

    if (options?.background) {
      cmd += ` --bg`;
    }

    return cmd;
  }

  /**
   * Generate Tailscale Serve command (local network only)
   */
  generateServeCommand(port: number, options?: { https?: boolean; path?: string }): string {
    let cmd = `tailscale serve`;

    if (options?.https !== false) {
      cmd += ` https:${port}`;
    } else {
      cmd += ` ${port}`;
    }

    if (options?.path) {
      cmd += ` ${options.path}`;
    }

    return cmd;
  }

  /**
   * Generate installation script
   */
  generateInstallScript(): string {
    return `#!/bin/bash
# Tailscale Installation Script
# Generated by BlackRoad OS

set -e

echo "Installing Tailscale..."

# Detect OS
if [ -f /etc/debian_version ]; then
    curl -fsSL https://tailscale.com/install.sh | sh
elif [ -f /etc/redhat-release ]; then
    curl -fsSL https://tailscale.com/install.sh | sh
elif [ "$(uname)" == "Darwin" ]; then
    brew install tailscale
else
    curl -fsSL https://tailscale.com/install.sh | sh
fi

echo "Starting Tailscale..."
sudo tailscale up${this.config.authKey ? ` --authkey=${this.config.authKey}` : ''}

echo "Tailscale installed and started!"
tailscale status
`;
  }
}

// =============================================================================
// SSH TUNNEL CLIENT
// =============================================================================

export interface SSHTunnelConfig {
  host: string;
  user: string;
  port?: number;
  keyFile?: string;
}

export class SSHTunnelClient {
  private readonly config: SSHTunnelConfig;

  constructor(config: SSHTunnelConfig) {
    this.config = {
      ...config,
      port: config.port || 22,
    };
  }

  /**
   * Generate local port forward command
   */
  localForward(localPort: number, remoteHost: string, remotePort: number): string {
    let cmd = `ssh -N -L ${localPort}:${remoteHost}:${remotePort}`;

    if (this.config.port !== 22) {
      cmd += ` -p ${this.config.port}`;
    }
    if (this.config.keyFile) {
      cmd += ` -i ${this.config.keyFile}`;
    }

    cmd += ` ${this.config.user}@${this.config.host}`;

    return cmd;
  }

  /**
   * Generate remote port forward command
   */
  remoteForward(remotePort: number, localHost: string, localPort: number): string {
    let cmd = `ssh -N -R ${remotePort}:${localHost}:${localPort}`;

    if (this.config.port !== 22) {
      cmd += ` -p ${this.config.port}`;
    }
    if (this.config.keyFile) {
      cmd += ` -i ${this.config.keyFile}`;
    }

    cmd += ` ${this.config.user}@${this.config.host}`;

    return cmd;
  }

  /**
   * Generate dynamic SOCKS proxy command
   */
  dynamicProxy(localPort: number): string {
    let cmd = `ssh -N -D ${localPort}`;

    if (this.config.port !== 22) {
      cmd += ` -p ${this.config.port}`;
    }
    if (this.config.keyFile) {
      cmd += ` -i ${this.config.keyFile}`;
    }

    cmd += ` ${this.config.user}@${this.config.host}`;

    return cmd;
  }

  /**
   * Generate SSH config entry
   */
  generateSSHConfig(name: string, tunnels?: {
    localForward?: { localPort: number; remoteHost: string; remotePort: number }[];
    remoteForward?: { remotePort: number; localHost: string; localPort: number }[];
  }): string {
    let config = `Host ${name}
  HostName ${this.config.host}
  User ${this.config.user}
  Port ${this.config.port}`;

    if (this.config.keyFile) {
      config += `\n  IdentityFile ${this.config.keyFile}`;
    }

    tunnels?.localForward?.forEach((fwd) => {
      config += `\n  LocalForward ${fwd.localPort} ${fwd.remoteHost}:${fwd.remotePort}`;
    });

    tunnels?.remoteForward?.forEach((fwd) => {
      config += `\n  RemoteForward ${fwd.remotePort} ${fwd.localHost}:${fwd.localPort}`;
    });

    return config;
  }

  /**
   * Generate autossh command for persistent tunnels
   */
  autosshCommand(localPort: number, remoteHost: string, remotePort: number): string {
    let cmd = `autossh -M 0 -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -N -L ${localPort}:${remoteHost}:${remotePort}`;

    if (this.config.port !== 22) {
      cmd += ` -p ${this.config.port}`;
    }
    if (this.config.keyFile) {
      cmd += ` -i ${this.config.keyFile}`;
    }

    cmd += ` ${this.config.user}@${this.config.host}`;

    return cmd;
  }
}

// =============================================================================
// UNIFIED TUNNEL MANAGER
// =============================================================================

export class TunnelManager {
  private cloudflare?: CloudflareTunnelClient;
  private ngrok?: NgrokClient;
  private localtunnel?: LocaltunnelClient;
  private tailscale?: TailscaleClient;
  private ssh?: SSHTunnelClient;

  /**
   * Configure Cloudflare Tunnel
   */
  configureCloudflare(apiToken: string, config: CloudflareTunnelConfig): this {
    this.cloudflare = new CloudflareTunnelClient(apiToken, config);
    return this;
  }

  /**
   * Configure ngrok
   */
  configureNgrok(config: NgrokConfig): this {
    this.ngrok = new NgrokClient(config);
    return this;
  }

  /**
   * Configure localtunnel
   */
  configureLocaltunnel(config?: LocaltunnelConfig): this {
    this.localtunnel = new LocaltunnelClient(config);
    return this;
  }

  /**
   * Configure Tailscale
   */
  configureTailscale(config?: TailscaleConfig): this {
    this.tailscale = new TailscaleClient(config);
    return this;
  }

  /**
   * Configure SSH tunnel
   */
  configureSSH(config: SSHTunnelConfig): this {
    this.ssh = new SSHTunnelClient(config);
    return this;
  }

  /**
   * Get configured provider clients
   */
  getProviders(): {
    cloudflare?: CloudflareTunnelClient;
    ngrok?: NgrokClient;
    localtunnel?: LocaltunnelClient;
    tailscale?: TailscaleClient;
    ssh?: SSHTunnelClient;
  } {
    return {
      cloudflare: this.cloudflare,
      ngrok: this.ngrok,
      localtunnel: this.localtunnel,
      tailscale: this.tailscale,
      ssh: this.ssh,
    };
  }

  /**
   * Generate quick start command for a provider
   */
  quickStart(provider: TunnelProvider, port: number): string {
    switch (provider) {
      case 'cloudflare':
        return `cloudflared tunnel --url http://localhost:${port}`;
      case 'ngrok':
        return this.ngrok?.generateCommand({ port }) || `ngrok http ${port}`;
      case 'localtunnel':
        return this.localtunnel?.generateCommand(port) || `lt --port ${port}`;
      case 'tailscale':
        return this.tailscale?.generateFunnelCommand(port) || `tailscale funnel ${port}`;
      case 'ssh':
        return this.ssh?.localForward(port, 'localhost', port) || `ssh -L ${port}:localhost:${port} user@host`;
      default:
        throw new Error(`Unknown tunnel provider: ${provider}`);
    }
  }
}

// =============================================================================
// FACTORY FUNCTIONS
// =============================================================================

/**
 * Create a tunnel manager with all providers
 */
export function createTunnelManager(): TunnelManager {
  return new TunnelManager();
}

/**
 * Create Cloudflare Tunnel client from environment
 */
export function createCloudflareTunnel(): CloudflareTunnelClient {
  const apiToken = process.env.CLOUDFLARE_API_TOKEN;
  const accountId = process.env.CLOUDFLARE_ACCOUNT_ID;

  if (!apiToken || !accountId) {
    throw new Error('CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID environment variables required');
  }

  return new CloudflareTunnelClient(apiToken, {
    accountId,
    tunnelId: process.env.CLOUDFLARE_TUNNEL_ID,
    tunnelName: process.env.CLOUDFLARE_TUNNEL_NAME,
  });
}

/**
 * Create ngrok client from environment
 */
export function createNgrokClient(): NgrokClient {
  const authToken = process.env.NGROK_AUTHTOKEN;

  if (!authToken) {
    throw new Error('NGROK_AUTHTOKEN environment variable required');
  }

  return new NgrokClient({
    authToken,
    region: process.env.NGROK_REGION as NgrokConfig['region'],
  });
}
